# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(960, 600)
        MainWindow.setMinimumSize(QtCore.QSize(960, 600))
        MainWindow.setMaximumSize(QtCore.QSize(960, 600))
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(20, 20, 760, 560))
        self.widget.setStyleSheet("background-color: rgb(70, 70, 70);")
        self.widget.setObjectName("widget")
        self.preButton = QtWidgets.QPushButton(self.widget)
        self.preButton.setGeometry(QtCore.QRect(270, 500, 50, 40))
        self.preButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.preButton.setStyleSheet("background-color: rgb(50, 50, 50);\n"
"color: rgb(170, 170, 170);")
        self.preButton.setObjectName("preButton")
        self.nextButton = QtWidgets.QPushButton(self.widget)
        self.nextButton.setGeometry(QtCore.QRect(460, 500, 50, 40))
        self.nextButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.nextButton.setStyleSheet("background-color: rgb(50, 50, 50);\n"
"color: rgb(170, 170, 170);")
        self.nextButton.setObjectName("nextButton")
        self.frameNumb = QtWidgets.QTextEdit(self.widget)
        self.frameNumb.setGeometry(QtCore.QRect(340, 500, 100, 40))
        self.frameNumb.setStyleSheet("background-color: rgb(50, 50, 50);\n"
"color: rgb(170, 170, 170);")
        self.frameNumb.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameNumb.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.frameNumb.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.frameNumb.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.frameNumb.setObjectName("frameNumb")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(790, 20, 160, 60))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("background-color: rgb(40, 40, 40);\n"
"color: rgb(170, 170, 170);")
        self.pushButton.setObjectName("pushButton")
        self.frameInfo = QtWidgets.QTextBrowser(self.centralwidget)
        self.frameInfo.setGeometry(QtCore.QRect(790, 90, 160, 131))
        self.frameInfo.setStyleSheet("background-color: rgb(40, 40, 40);\n"
"color: rgb(170, 170, 170);")
        self.frameInfo.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameInfo.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.frameInfo.setObjectName("frameInfo")
        self.selectModel = QtWidgets.QComboBox(self.centralwidget)
        self.selectModel.setGeometry(QtCore.QRect(790, 230, 160, 50))
        self.selectModel.setStyleSheet("background-color: rgb(40, 40, 40);\n"
"color: rgb(170, 170, 170);")
        self.selectModel.setObjectName("selectModel")
        self.selectModel.addItem("")
        self.selectObject = QtWidgets.QComboBox(self.centralwidget)
        self.selectObject.setGeometry(QtCore.QRect(790, 290, 160, 50))
        self.selectObject.setStyleSheet("background-color: rgb(40, 40, 40);\n"
"color: rgb(170, 170, 170);")
        self.selectObject.setObjectName("selectObject")
        self.selectObject.addItem("")
        self.selectObject.addItem("")
        self.selectObject.addItem("")
        self.selectObject.addItem("")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(790, 350, 160, 60))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("background-color: rgb(40, 40, 40);\n"
"color: rgb(170, 170, 170);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.finishCue = QtWidgets.QTextBrowser(self.centralwidget)
        self.finishCue.setGeometry(QtCore.QRect(790, 419, 160, 161))
        self.finishCue.setStyleSheet("background-color: rgb(40, 40, 40);\n"
"color: rgb(170, 170, 170);")
        self.finishCue.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.finishCue.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.finishCue.setObjectName("finishCue")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        ###############
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.preButton.setText(_translate("MainWindow", "←"))
        self.nextButton.setText(_translate("MainWindow", "→"))
        self.frameNumb.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "Input File"))
        self.selectModel.setItemText(0, _translate("MainWindow", "--Select Model--"))
        self.selectModel.setItemText(1, _translate("MainWindow", "yolov7"))
        self.selectModel.setItemText(2, _translate("MainWindow", "mask-rcnn"))

        self.selectObject.setItemText(0, _translate("MainWindow", "--Select Object--"))
        self.selectObject.setItemText(1, _translate("MainWindow", "car"))
        self.selectObject.setItemText(2, _translate("MainWindow", "person"))
        self.selectObject.setItemText(3, _translate("MainWindow", "bicycle"))
        self.pushButton_2.setText(_translate("MainWindow", "AutoLabel"))
