# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Startui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Start(object):
    def setupUi(self, Start):
        Start.setObjectName("Start")
        Start.resize(545, 300)
        self.verticalLayoutWidget = QtWidgets.QWidget(Start)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 0, 171, 281))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setMinimumSize(QtCore.QSize(0, 20))
        self.label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.Pic2VidButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Pic2VidButton.setObjectName("Pic2VidButton")
        self.verticalLayout.addWidget(self.Pic2VidButton)
        self.Vid2PicButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Vid2PicButton.setObjectName("Vid2PicButton")
        self.verticalLayout.addWidget(self.Vid2PicButton)
        self.BBoxLabelImgButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.BBoxLabelImgButton.setObjectName("BBoxLabelImgButton")
        self.verticalLayout.addWidget(self.BBoxLabelImgButton)
        self.CloseButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.CloseButton.setObjectName("CloseButton")
        self.verticalLayout.addWidget(self.CloseButton)
        self.label_2 = QtWidgets.QLabel(Start)
        self.label_2.setGeometry(QtCore.QRect(220, 90, 301, 101))
        self.label_2.setStyleSheet("font: 22pt \"Segoe Script\";\n"
"background-color: rgb(255, 170, 255);")
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Start)
        QtCore.QMetaObject.connectSlotsByName(Start)

    def retranslateUi(self, Start):
        _translate = QtCore.QCoreApplication.translate
        Start.setWindowTitle(_translate("Start", "Form"))
        self.label.setText(_translate("Start", "Select function:"))
        self.Pic2VidButton.setText(_translate("Start", "Frame to Video"))
        self.Vid2PicButton.setText(_translate("Start", "Video to Frame"))
        self.BBoxLabelImgButton.setText(_translate("Start", "Label"))
        self.CloseButton.setText(_translate("Start", "close"))
        self.label_2.setText(_translate("Start", "AutoLabelTool \n"
"for video"))
